spring:
  mail:
    host: smtp.163.com
    username: mnzdna@163.com
    password: *****
    port: 465
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactor

  application:
    name: know-hub-ai

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost/know-hub-app
    type: com.zaxxer.hikari.HikariDataSource
    # hikari连接池配置
    hikari:
      #连接池名
      pool-name: HikariCP
      #最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟
      idle-timeout: 600000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒
      connection-timeout: 30000
      # 连接测试query
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true
    open-in-view: true

  ai:
    embedding:
      transformer:
        tokenizer:
          options:
            padding: true
    openai:
      api-key: sk-W9kYeE3Jf*******6B96fAd460353Dc7a
      base-url: https://api.mnzdna.xyz


minio:
  endpoint: ${MINIO_ENDPOINT:http://127.0.0.1:9000/}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket-name: ${BUCKET_NAME:know-hub}

server:
  port: 8818
  address: 0.0.0.0

application:
  domain: http://localhost:8818
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days